version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "projects"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./src/main/resources/sql/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"